TABLE_ (CUSTOMERS)
	INT_	(CUST_ID) NOT_NULL PRIMARY_KEY AUTO_INCREMENT
	STRING_ (CUSTNAME, 150) NOT_NULL
	STRING_ (EMAIL, 150)
	STRING_ (CONTACT, 150)
	STRING_ (ADDRESS, 150)
	STRING_ (CITY, 50)
	STRING_ (STATE, 20)
	STRING_ (ZIP, 10)
	INT_ (CTY_NUM) REFERENCES(COUNTIES(COUNTY_NUM))
	INT_ (TAXABLE) NOT_NULL
END_TABLE

TABLE_ (INVOICES)
	INT64_ (INVOICENUMBER)    NOT_NULL PRIMARY_KEY
	INT_ (CUSTOMERID)    REFERENCES(CUSTOMERS(CUST_ID))
	DATE_ (TRANSACTIONDATE)
	STRING_ (TERMS, 20) NOT_NULL
	DOUBLE_ (NONTAXABLESUB)
	DOUBLE_ (TAXABLESUB) 	
	DOUBLE_ (TAX)
	DOUBLE_ (GRANDTOTAL)
	DOUBLE_ (AMTPAID)
	DATE_ (DATEPAID)
	INT_ (STATUS)
END_TABLE

TABLE_ (PRODUCTS)
	INT_ (PROD_ID)	NOT_NULL PRIMARY_KEY AUTO_INCREMENT
	STRING_ (PRODNAME, 150)	NOT_NULL
	STRING_ (PRODDESCRIPTION, 200)
	DATE_ (DATEPURCHASED)
	DOUBLE_ (COST)	NOT_NULL
	INT64_ (INVOICEID)	NOT_NULL REFERENCES(INVOICES(INVOICENUMBER))
END_TABLE

TABLE_ (LINEITEMS)
	INT_ (LINEITEM_ID)	NOT_NULL PRIMARY_KEY AUTO_INCREMENT
	INT_ (PRODUCTNAME) NOT_NULL
	STRING_ (DESCRIPTION, 200)
	DOUBLE_ (PRICE)	 NOT_NULL
	DOUBLE_ (QTY)	 NOT_NULL
	DOUBLE_ (TOTAL)	 NOT_NULL
	INT64_ (INVOICEIDNUMBER)	 NOT_NULL REFERENCES(INVOICES(INVOICENUMBER))
	INT_ (ISTAXABLE)	 NOT_NULL
END_TABLE

TABLE_ (TYPES)
	INT_ (TYPENUM) NOT_NULL PRIMARY_KEY AUTO_INCREMENT
	STRING_ (TYPENAME, 100) NOT_NULL
	STRING_ (TYPEDESCR, 200)
	DOUBLE_ (TYPEQUANT) NOT_NULL
	DOUBLE_ (TYPECOST) NOT_NULL
	INT_ (TYPETAXABLE) NOT_NULL
END_TABLE

TABLE_ (COUNTIES)
	INT_ (COUNTY_NUM) NOT_NULL PRIMARY_KEY AUTO_INCREMENT
	STRING_ (COUNTY_NAME, 100) NOT_NULL
END_TABLE
